digit = "0".."9"
lowercase = "a".."z"
uppercase = "A".."Z"
letter = lowercase | uppercase
punctuation = "`" | "~" |
						  "!" | "@" | "#" | "$" | "%" | "^" | "&" | "*" |
							"(" | ")" | "[" | "]" | "{" | "}" |
							"," | "." | ";" | ":" | "/" | "\\" | "|"
char = digit | letter | punctuation

unary_operator = "~"
binary_operator = "+" | "-" | "*" | "**" | "/" | "//" | "%" |
								  "^" | "~" | "&" | "|" | "<<" | ">>" |
									"." | ".." | ":" |
									"<" | ">" | "<=" | ">=" | "==" | "!="
op = unary_operator | binary_operator
operation = op operand -> unary |
						operand op operand -> binary
